### ISSUE TITLE
Filesystem

### ISSUE THREAD

**Issue by mulderr** [WebGHC/musl#2]
Hi!

I have been following this project with increasing interest. I think I may be able to help a bit with the syscalls but I would like to open a little discussion here about how we should proceed with the implementation. Right now, as I understand it, there have been no particular commitments made ex. in the area of the VFS so there seem to be *a lot* of open questions.

What do you think about bringing in something like [BrowserFS](https://github.com/jvilk/BrowserFS) as a dependency? It is currently around 250K minified and seems to contain some functionality we may never use like `ZipFS`, `IsoFS`, `Dropbox` (?) and so may be a tad too general, so initially I have mixed feelings about it.

If we do start from scratch, what would be the angle of approach. Do we for example want to start with memory or sessionStorage/localStorage only for simplicity and later find ways to give user ability to specify a kind of `fstab`-ish list of mountpoints and choose what kind of storage they want for each of them (memory, session, local, other...)?

The two most important things to support, which most people are likely to use, are obviously in-memory and session/localStorage. We can probably do that with a smaller footprint at least, if not in a simpler way as well, without the added generality to handle additional backends. But if there are already good indications that we could need more fancy stuff then maybe it's better to go with BrowserFS from the start.

What do you think?

**Comment by ElvishJerricco** [comment]
I thinking starting with BrowserFS would be a good idea. Although I'm sure we could build something else with a smaller footprint, that seems a little out of scope at the moment. If it's able to accommodate the majority of our file system syscalls, we should probably just go with it and reevaluate later.

**Comment by mulderr** [comment]
Sounds like a plan. First draft of open/close and read/write in PR #3.

**Comment by mulderr** [comment]
I'm going to bite the bullet here and try to implement everything I can going (mostly) from top to bottom. See if/where things break. More in PR #4.

We may need some proper tests eventually.

**Comment by mulderr** [comment]
I think this can be closed now. Further discussion and/or PRs should probably continue in webabi.
