### ISSUE TITLE
Factor JS out into separate repo

### ISSUE THREAD

**Issue by ElvishJerricco** [WebGHC/musl#6]
I think it would be good to treat the JS as a kernel, as far as musl is concerned. So musl should simply know the syscall ABI, and the JS should implement it in a completely separate repo. Keeping JS out of the musl repo increases the likelihood of eventually getting wasm support upstreamed into musl proper.

**Comment by ElvishJerricco** [comment]
Going to wait on #4 to be merged before doing this.

**Comment by ElvishJerricco** [comment]
What should we call it? I was kind of thinking "wasm-bone" or something, to make a joke about "musl and bone" :P

**Comment by mulderr** [comment]
Haha, wasm-bone sounds good to me as long as R integration is not in the realm of possibility :P

On the other hand I'm thinking, how much of this will really be wasm specific. It kind of looks like it might be a mostly "generic" JS kernel-like thingy. We're not really shooting for that anytime soon though so I'm +1 on wasm-bone.

**Comment by ElvishJerricco** [comment]
Ended up calling it [`webabi`](https://github.com/WebGHC/webabi)
